name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.1)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update manifest.json version
        run: |
          # Remove 'v' prefix from version if present
          VERSION=${{ inputs.version }}
          VERSION=${VERSION#v}

          # Update version in manifest.json
          sed -i 's/"version": "[^"]*"/"version": "'"$VERSION"'"/' manifest.json

          # Commit the change only if there are changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "Version already up to date at $VERSION"
          else
            git commit -m "Bump version to $VERSION"
            git push
          fi

      - name: Create release package
        run: |
          zip -r tabguard-${{ inputs.version }}.zip . \
            -x "*.git*" \
            -x ".DS_Store" \
            -x "*.zip" \
            -x ".github/*"

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ inputs.version }} \
            tabguard-${{ inputs.version }}.zip \
            --title "TabGuard ${{ inputs.version }}" \
            ${{ inputs.prerelease && '--prerelease' || '' }} \
            --notes "## Installation

          1. Download \`tabguard-${{ inputs.version }}.zip\` below
          2. Extract the zip file
          3. Open \`chrome://extensions/\` (or \`brave://extensions/\`)
          4. Enable \"Developer mode\" (toggle in top-right)
          5. Click \"Load unpacked\"
          6. Select the extracted folder

          ## Browser Compatibility

          - ✅ Google Chrome (Manifest V3)
          - ✅ Brave Browser
          - ✅ Microsoft Edge
          - ✅ Any Chromium-based browser

          See [README](https://github.com/${{ github.repository }}) for full feature list and usage instructions."
